export const bairrosSP: string[] = [
  'Agua Rasa',
  'Alto De Pinheiros',
  'Anhanguera',
  'Aricanduva',
  'Artur Alvim',
  'Barra Funda',
  'Bela Vista',
  'Belem',
  'Bom Retiro',
  'Brasilandia',
  'Butanta',
  'Cachoeirinha',
  'Cambuci',
  'Campo Belo',
  'Campo Grande',
  'Campo Limpo',
  'Cangaiba',
  'Capao Redondo',
  'Carrao',
  'Casa Verde',
  'Cidade Ademar',
  'Cidade Dutra',
  'Cidade Lider',
  'Cidade Tiradentes',
  'Consolacao',
  'Cursino',
  'Ermelino Matarazzo',
  'Freguesia Do O',
  'Grajau',
  'Guaianases',
  'Iguatemi',
  'Ipiranga',
  'Itaim Bibi',
  'Itaim Paulista',
  'Itaquera',
  'Jabaquara',
  'Jacana',
  'Jaguara',
  'Jaguare',
  'Jaragua',
  'Jardim Angela',
  'Jardim Helena',
  'Jardim Paulista',
  'Jardim Sao Luis',
  'Lapa',
  'Liberdade',
  'Limao',
  'Mandaqui',
  'Marsilac',
  'Moema',
  'Mooca',
  'Morumbi',
  'Parelheiros',
  'Pari',
  'Parque Do Carmo',
  'Penha',
  'Perdizes',
  'Pinheiros',
  'Ponte Rasa',
  'Raposo Tavares',
  'Republica',
  'Rio Pequeno',
  'Sacoma',
  'Santa Cecilia',
  'Santana',
  'Santo Amaro',
  'Sao Domingos',
  'Sao Lucas',
  'Sao Mateus',
  'Sao Miguel Paulista',
  'Sao Rafael',
  'Sapopemba',
  'Saude',
  'Se',
  'Tatuape',
  'Tremembe',
  'Tucuruvi',
  'Vila Andrade',
  'Vila Curuca',
  'Vila Formosa',
  'Vila Guilherme',
  'Vila Jacui',
  'Vila Leopoldina',
  'Vila Maria',
  'Vila Mariana',
  'Vila Matilde',
  'Vila Medeiros',
  'Vila Prudente',
  'Vila Sonia'
]
